import 'dart:convert';

final Map mockCurrentWeatherData = jsonDecode('''
{
   "coord":{
      "lon":139.6917,
      "lat":35.6895
   },
   "weather":[
      {
         "id":801,
         "main":"Clouds",
         "description":"few clouds",
         "icon":"02d"
      }
   ],
   "base":"stations",
   "main":{
      "temp":28.59,
      "feels_like":32.35,
      "temp_min":26.48,
      "temp_max":30.31,
      "pressure":1008,
      "humidity":73
   },
   "visibility":10000,
   "wind":{
      "speed":2.06,
      "deg":100
   },
   "clouds":{
      "all":20
   },
   "dt":1657494313,
   "sys":{
      "type":2,
      "id":2038398,
      "country":"JP",
      "sunrise":1657481626,
      "sunset":1657533548
   },
   "timezone":32400,
   "id":1850144,
   "name":"Tokyo",
   "cod":200
}
''');

final Map mockWeatherForecastData = jsonDecode('''
{
   "cod":"200",
   "message":0,
   "cnt":40,
   "list":[
      {
         "dt":1657497600,
         "main":{
            "temp":29.31,
            "feels_like":33.62,
            "temp_min":28.2,
            "temp_max":29.31,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1003,
            "humidity":71,
            "temp_kf":1.11
         },
         "weather":[
            {
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02d"
            }
         ],
         "clouds":{
            "all":20
         },
         "wind":{
            "speed":1.55,
            "deg":107,
            "gust":1.38
         },
         "visibility":10000,
         "pop":0,
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-11 00:00:00"
      },
      {
         "dt":1657508400,
         "main":{
            "temp":29.98,
            "feels_like":33.41,
            "temp_min":29.98,
            "temp_max":31.31,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":63,
            "temp_kf":-1.33
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":43
         },
         "wind":{
            "speed":2.04,
            "deg":142,
            "gust":1.84
         },
         "visibility":10000,
         "pop":0,
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-11 03:00:00"
      },
      {
         "dt":1657519200,
         "main":{
            "temp":31.63,
            "feels_like":34.39,
            "temp_min":31.63,
            "temp_max":32.79,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1002,
            "humidity":53,
            "temp_kf":-1.16
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":69
         },
         "wind":{
            "speed":4.93,
            "deg":173,
            "gust":3.84
         },
         "visibility":10000,
         "pop":0.02,
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-11 06:00:00"
      },
      {
         "dt":1657530000,
         "main":{
            "temp":29.75,
            "feels_like":32.36,
            "temp_min":29.75,
            "temp_max":29.75,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1003,
            "humidity":60,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":87
         },
         "wind":{
            "speed":6.42,
            "deg":180,
            "gust":6.86
         },
         "visibility":10000,
         "pop":0.04,
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-11 09:00:00"
      },
      {
         "dt":1657540800,
         "main":{
            "temp":27.49,
            "feels_like":29.71,
            "temp_min":27.49,
            "temp_max":27.49,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":1005,
            "humidity":70,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":93
         },
         "wind":{
            "speed":4.56,
            "deg":172,
            "gust":4.65
         },
         "visibility":10000,
         "pop":0.03,
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-11 12:00:00"
      },
      {
         "dt":1657551600,
         "main":{
            "temp":26.45,
            "feels_like":26.45,
            "temp_min":26.45,
            "temp_max":26.45,
            "pressure":1009,
            "sea_level":1009,
            "grnd_level":1004,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.54,
            "deg":150,
            "gust":2.5
         },
         "visibility":10000,
         "pop":0.01,
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-11 15:00:00"
      },
      {
         "dt":1657562400,
         "main":{
            "temp":25.88,
            "feels_like":26.51,
            "temp_min":25.88,
            "temp_max":25.88,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1003,
            "humidity":76,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.3,
            "deg":144,
            "gust":2.25
         },
         "visibility":10000,
         "pop":0,
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-11 18:00:00"
      },
      {
         "dt":1657573200,
         "main":{
            "temp":25.53,
            "feels_like":26.18,
            "temp_min":25.53,
            "temp_max":25.53,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1004,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.69,
            "deg":146,
            "gust":2.78
         },
         "visibility":10000,
         "pop":0.19,
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-11 21:00:00"
      },
      {
         "dt":1657584000,
         "main":{
            "temp":26.52,
            "feels_like":26.52,
            "temp_min":26.52,
            "temp_max":26.52,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1003,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.27,
            "deg":144,
            "gust":3.41
         },
         "visibility":10000,
         "pop":0.38,
         "rain":{
            "3h":0.11
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-12 00:00:00"
      },
      {
         "dt":1657594800,
         "main":{
            "temp":25.99,
            "feels_like":25.99,
            "temp_min":25.99,
            "temp_max":25.99,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.36,
            "deg":166,
            "gust":4.62
         },
         "visibility":10000,
         "pop":0.77,
         "rain":{
            "3h":1.35
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-12 03:00:00"
      },
      {
         "dt":1657605600,
         "main":{
            "temp":28.03,
            "feels_like":30.21,
            "temp_min":28.03,
            "temp_max":28.03,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":66,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":5.22,
            "deg":161,
            "gust":5.65
         },
         "visibility":10000,
         "pop":0.94,
         "rain":{
            "3h":0.67
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-12 06:00:00"
      },
      {
         "dt":1657616400,
         "main":{
            "temp":26.48,
            "feels_like":26.48,
            "temp_min":26.48,
            "temp_max":26.48,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":97
         },
         "wind":{
            "speed":4.67,
            "deg":168,
            "gust":5.51
         },
         "visibility":10000,
         "pop":0.95,
         "rain":{
            "3h":0.63
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-12 09:00:00"
      },
      {
         "dt":1657627200,
         "main":{
            "temp":25.7,
            "feels_like":26.39,
            "temp_min":25.7,
            "temp_max":25.7,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":94
         },
         "wind":{
            "speed":2.65,
            "deg":126,
            "gust":3.41
         },
         "visibility":10000,
         "pop":1,
         "rain":{
            "3h":1.58
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-12 12:00:00"
      },
      {
         "dt":1657638000,
         "main":{
            "temp":24.61,
            "feels_like":25.35,
            "temp_min":24.61,
            "temp_max":24.61,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":90
         },
         "wind":{
            "speed":3.11,
            "deg":79,
            "gust":3.7
         },
         "visibility":10000,
         "pop":1,
         "rain":{
            "3h":2.97
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-12 15:00:00"
      },
      {
         "dt":1657648800,
         "main":{
            "temp":24.23,
            "feels_like":24.93,
            "temp_min":24.23,
            "temp_max":24.23,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1002,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":95
         },
         "wind":{
            "speed":3.1,
            "deg":87,
            "gust":3.94
         },
         "visibility":10000,
         "pop":1,
         "rain":{
            "3h":1.95
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-12 18:00:00"
      },
      {
         "dt":1657659600,
         "main":{
            "temp":23.98,
            "feels_like":24.71,
            "temp_min":23.98,
            "temp_max":23.98,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.44,
            "deg":81,
            "gust":4.1
         },
         "visibility":10000,
         "pop":0.88,
         "rain":{
            "3h":1.03
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-12 21:00:00"
      },
      {
         "dt":1657670400,
         "main":{
            "temp":24.14,
            "feels_like":24.83,
            "temp_min":24.14,
            "temp_max":24.14,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1003,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":4.02,
            "deg":76,
            "gust":4.52
         },
         "visibility":10000,
         "pop":1,
         "rain":{
            "3h":1.04
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-13 00:00:00"
      },
      {
         "dt":1657681200,
         "main":{
            "temp":25.61,
            "feels_like":26.24,
            "temp_min":25.61,
            "temp_max":25.61,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":98
         },
         "wind":{
            "speed":4.05,
            "deg":91,
            "gust":4.23
         },
         "visibility":10000,
         "pop":0.65,
         "rain":{
            "3h":0.6
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-13 03:00:00"
      },
      {
         "dt":1657692000,
         "main":{
            "temp":26.52,
            "feels_like":26.52,
            "temp_min":26.52,
            "temp_max":26.52,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":72,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":96
         },
         "wind":{
            "speed":3.85,
            "deg":116,
            "gust":3.77
         },
         "visibility":10000,
         "pop":0.8,
         "rain":{
            "3h":0.89
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-13 06:00:00"
      },
      {
         "dt":1657702800,
         "main":{
            "temp":25.29,
            "feels_like":25.91,
            "temp_min":25.29,
            "temp_max":25.29,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":91
         },
         "wind":{
            "speed":4.05,
            "deg":123,
            "gust":4.43
         },
         "visibility":10000,
         "pop":0.86,
         "rain":{
            "3h":1.4
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-13 09:00:00"
      },
      {
         "dt":1657713600,
         "main":{
            "temp":24.47,
            "feels_like":25.11,
            "temp_min":24.47,
            "temp_max":24.47,
            "pressure":1008,
            "sea_level":1008,
            "grnd_level":1003,
            "humidity":82,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":96
         },
         "wind":{
            "speed":3.81,
            "deg":107,
            "gust":4.65
         },
         "visibility":10000,
         "pop":0.94,
         "rain":{
            "3h":1.52
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-13 12:00:00"
      },
      {
         "dt":1657724400,
         "main":{
            "temp":24,
            "feels_like":24.65,
            "temp_min":24,
            "temp_max":24,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":84,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.26,
            "deg":109,
            "gust":4.02
         },
         "visibility":10000,
         "pop":0.56,
         "rain":{
            "3h":0.45
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-13 15:00:00"
      },
      {
         "dt":1657735200,
         "main":{
            "temp":23.76,
            "feels_like":24.41,
            "temp_min":23.76,
            "temp_max":23.76,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.3,
            "deg":109,
            "gust":4.18
         },
         "visibility":10000,
         "pop":0.54,
         "rain":{
            "3h":0.42
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-13 18:00:00"
      },
      {
         "dt":1657746000,
         "main":{
            "temp":23.61,
            "feels_like":24.27,
            "temp_min":23.61,
            "temp_max":23.61,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":86,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.57,
            "deg":98,
            "gust":4.74
         },
         "visibility":10000,
         "pop":0.66,
         "rain":{
            "3h":0.85
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-13 21:00:00"
      },
      {
         "dt":1657756800,
         "main":{
            "temp":24.23,
            "feels_like":24.85,
            "temp_min":24.23,
            "temp_max":24.23,
            "pressure":1007,
            "sea_level":1007,
            "grnd_level":1002,
            "humidity":82,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.14,
            "deg":90,
            "gust":3.74
         },
         "visibility":10000,
         "pop":0.84,
         "rain":{
            "3h":1.38
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-14 00:00:00"
      },
      {
         "dt":1657767600,
         "main":{
            "temp":26.46,
            "feels_like":26.46,
            "temp_min":26.46,
            "temp_max":26.46,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":70,
            "temp_kf":0
         },
         "weather":[
            {
               "id":501,
               "main":"Rain",
               "description":"moderate rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.44,
            "deg":106,
            "gust":3.85
         },
         "visibility":7699,
         "pop":0.93,
         "rain":{
            "3h":3.2
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-14 03:00:00"
      },
      {
         "dt":1657778400,
         "main":{
            "temp":25.99,
            "feels_like":25.99,
            "temp_min":25.99,
            "temp_max":25.99,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":72,
            "temp_kf":0
         },
         "weather":[
            {
               "id":501,
               "main":"Rain",
               "description":"moderate rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.94,
            "deg":126,
            "gust":4.54
         },
         "visibility":8122,
         "pop":0.93,
         "rain":{
            "3h":4.8
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-14 06:00:00"
      },
      {
         "dt":1657789200,
         "main":{
            "temp":24.79,
            "feels_like":25.36,
            "temp_min":24.79,
            "temp_max":24.79,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1001,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":501,
               "main":"Rain",
               "description":"moderate rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.7,
            "deg":131,
            "gust":4.56
         },
         "visibility":10000,
         "pop":0.95,
         "rain":{
            "3h":3.06
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-14 09:00:00"
      },
      {
         "dt":1657800000,
         "main":{
            "temp":23.61,
            "feels_like":24.25,
            "temp_min":23.61,
            "temp_max":23.61,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":4.08,
            "deg":132,
            "gust":5.73
         },
         "visibility":9565,
         "pop":1,
         "rain":{
            "3h":2.44
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-14 12:00:00"
      },
      {
         "dt":1657810800,
         "main":{
            "temp":23.39,
            "feels_like":24.03,
            "temp_min":23.39,
            "temp_max":23.39,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":86,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.6,
            "deg":130,
            "gust":5.34
         },
         "visibility":10000,
         "pop":0.79,
         "rain":{
            "3h":1.27
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-14 15:00:00"
      },
      {
         "dt":1657821600,
         "main":{
            "temp":23.11,
            "feels_like":23.75,
            "temp_min":23.11,
            "temp_max":23.11,
            "pressure":1004,
            "sea_level":1004,
            "grnd_level":999,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.85,
            "deg":125,
            "gust":5.91
         },
         "visibility":10000,
         "pop":0.8,
         "rain":{
            "3h":0.85
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-14 18:00:00"
      },
      {
         "dt":1657832400,
         "main":{
            "temp":23.25,
            "feels_like":23.9,
            "temp_min":23.25,
            "temp_max":23.25,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":99
         },
         "wind":{
            "speed":4.24,
            "deg":132,
            "gust":6.43
         },
         "visibility":10000,
         "pop":0.71,
         "rain":{
            "3h":0.59
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-14 21:00:00"
      },
      {
         "dt":1657843200,
         "main":{
            "temp":23.65,
            "feels_like":24.34,
            "temp_min":23.65,
            "temp_max":23.65,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.94,
            "deg":152,
            "gust":6.13
         },
         "visibility":10000,
         "pop":0.74,
         "rain":{
            "3h":0.58
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-15 00:00:00"
      },
      {
         "dt":1657854000,
         "main":{
            "temp":26.05,
            "feels_like":26.05,
            "temp_min":26.05,
            "temp_max":26.05,
            "pressure":1004,
            "sea_level":1004,
            "grnd_level":999,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":95
         },
         "wind":{
            "speed":3.34,
            "deg":172,
            "gust":4.65
         },
         "visibility":10000,
         "pop":0.6,
         "rain":{
            "3h":0.64
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-15 03:00:00"
      },
      {
         "dt":1657864800,
         "main":{
            "temp":26.31,
            "feels_like":26.31,
            "temp_min":26.31,
            "temp_max":26.31,
            "pressure":1004,
            "sea_level":1004,
            "grnd_level":999,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":90
         },
         "wind":{
            "speed":1.83,
            "deg":208,
            "gust":4.32
         },
         "visibility":10000,
         "pop":0.56,
         "rain":{
            "3h":0.68
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-15 06:00:00"
      },
      {
         "dt":1657875600,
         "main":{
            "temp":25.63,
            "feels_like":26.29,
            "temp_min":25.63,
            "temp_max":25.63,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":0.69,
            "deg":243,
            "gust":3.77
         },
         "visibility":10000,
         "pop":0.48,
         "rain":{
            "3h":0.22
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-15 09:00:00"
      },
      {
         "dt":1657886400,
         "main":{
            "temp":24.83,
            "feels_like":25.48,
            "temp_min":24.83,
            "temp_max":24.83,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":1.04,
            "deg":338,
            "gust":3.11
         },
         "visibility":10000,
         "pop":0.49,
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-15 12:00:00"
      },
      {
         "dt":1657897200,
         "main":{
            "temp":23.94,
            "feels_like":24.64,
            "temp_min":23.94,
            "temp_max":23.94,
            "pressure":1006,
            "sea_level":1006,
            "grnd_level":1001,
            "humidity":86,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":0.65,
            "deg":319,
            "gust":2.23
         },
         "visibility":10000,
         "pop":0.58,
         "rain":{
            "3h":0.35
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-15 15:00:00"
      },
      {
         "dt":1657908000,
         "main":{
            "temp":23.8,
            "feels_like":24.53,
            "temp_min":23.8,
            "temp_max":23.8,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1000,
            "humidity":88,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":1.74,
            "deg":124,
            "gust":3.21
         },
         "visibility":10000,
         "pop":0.59,
         "rain":{
            "3h":0.25
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2022-07-15 18:00:00"
      },
      {
         "dt":1657918800,
         "main":{
            "temp":24.28,
            "feels_like":25.04,
            "temp_min":24.28,
            "temp_max":24.28,
            "pressure":1005,
            "sea_level":1005,
            "grnd_level":1001,
            "humidity":87,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":4,
            "deg":148,
            "gust":6.63
         },
         "visibility":10000,
         "pop":0.71,
         "rain":{
            "3h":0.3
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2022-07-15 21:00:00"
      }
   ],
   "city":{
      "id":1850144,
      "name":"Tokyo",
      "coord":{
         "lat":35.6895,
         "lon":139.6917
      },
      "country":"JP",
      "population":12445327,
      "timezone":32400,
      "sunrise":1657481626,
      "sunset":1657533548
   }
}
''');

final Map mockTimeData = jsonDecode('''
{
   "year":2022,
   "month":7,
   "day":11,
   "hour":8,
   "minute":38,
   "seconds":15,
   "milliSeconds":645,
   "dateTime":"2022-07-11T08:38:15.6456345",
   "date":"07/11/2022",
   "time":"08:38",
   "timeZone":"Asia/Tokyo",
   "dayOfWeek":"Monday",
   "dstActive":false
}
''');

final Map mockAirQualityData = jsonDecode('''
{
   "coord":{
      "lon":139.6917,
      "lat":35.6895
   },
   "list":[
      {
         "main":{
            "aqi":2
         },
         "components":{
            "co":243.66,
            "no":23.47,
            "no2":39.41,
            "o3":6.97,
            "so2":28.37,
            "pm2_5":17.09,
            "pm10":25.69,
            "nh3":0.15
         },
         "dt":1657497600
      }
   ]
}
''');
