import 'data_service.dart';
import 'location_data.dart';

DataService dataService = DataService();

final allLocations = <LocationData>[
  LocationData('New York', dataService),
  LocationData('Tokyo', dataService),
  LocationData('London', dataService),
  LocationData('Los Angeles', dataService),
  LocationData('Singapore', dataService),
  LocationData('Paris', dataService),
  LocationData('Chicago', dataService),
  LocationData('Boston', dataService),
  LocationData('San Francisco', dataService),
  LocationData('Toronto', dataService),
  LocationData('Melbourne', dataService),
  LocationData('Berlin', dataService),
  LocationData('Dallas', dataService),
  LocationData('Seoul', dataService),
  LocationData('Sydney', dataService),
  LocationData('Seattle', dataService),
  LocationData('Houston', dataService),
  LocationData('Atlanta', dataService),
  LocationData('Washington DC', dataService),
  LocationData('Miami', dataService),
  LocationData('Barcelona', dataService),
  LocationData('Montréal', dataService),
  LocationData('San Diego', dataService),
  LocationData('Philadelphia', dataService),
  LocationData('Vienna', dataService),
  LocationData('Beijing', dataService),
  LocationData('Munich', dataService),
  LocationData('Madrid', dataService),
  LocationData('Milan', dataService),
  LocationData('Amsterdam', dataService),
  LocationData('Dubai', dataService),
  LocationData('Stockholm', dataService),
  LocationData('Shanghai', dataService),
  LocationData('Austin', dataService),
  LocationData('Denver', dataService),
  LocationData('Vancouver', dataService),
  LocationData('Osaka', dataService),
  LocationData('Moscow', dataService),
  LocationData('Portland', dataService),
  LocationData('Las Vegas', dataService),
  LocationData('Tel Aviv', dataService),
  LocationData('Oslo', dataService),
  LocationData('Istanbul', dataService),
  LocationData('Taipei', dataService),
  LocationData('Rome', dataService),
  LocationData('Hamburg', dataService),
  LocationData('Copenhagen', dataService),
  LocationData('Brisbane', dataService),
  LocationData('Oakland', dataService),
  LocationData('Orlando', dataService),
  LocationData('Baltimore', dataService),
  LocationData('Dublin', dataService),
  LocationData('Shenzhen', dataService),
  LocationData('Québec', dataService),
  LocationData('Detroit', dataService),
  LocationData('Hong Kong', dataService),
  LocationData('Manchester', dataService),
  LocationData('Helsinki', dataService),
  LocationData('Minneapolis', dataService),
  LocationData('Phoenix', dataService),
  LocationData('Prague', dataService),
  LocationData('Zürich', dataService),
  LocationData('Frankfurt', dataService),
  LocationData('Sacramento', dataService),
  LocationData('Brussels', dataService),
  LocationData('Nashville', dataService),
  LocationData('São Paulo', dataService),
  LocationData('Newark', dataService),
  LocationData('Buenos Aires', dataService),
  LocationData('San Antonio', dataService),
  LocationData('Bangkok', dataService),
  LocationData('Santa Ana', dataService),
  LocationData('Tampa', dataService),
  LocationData('Guangzhou', dataService),
  LocationData('Abu Dhabi', dataService),
  LocationData('Lyon', dataService),
  LocationData('Düsseldorf', dataService),
  LocationData('Athens', dataService),
  LocationData('Budapest', dataService),
  LocationData('Kyoto', dataService),
  LocationData('Kuala Lumpur', dataService),
  LocationData('Stuttgart', dataService),
  LocationData('Rotterdam', dataService),
  LocationData('Fort Lauderdale', dataService),
  LocationData('Mumbai', dataService),
  LocationData('Charlotte', dataService),
  LocationData('Mexico City', dataService),
  LocationData('Riverside', dataService),
  LocationData('Calgary', dataService),
  LocationData('Pittsburgh', dataService),
  LocationData('Busan', dataService),
  LocationData('Cologne', dataService),
  LocationData('Raleigh', dataService),
  LocationData('Kansas City', dataService),
  LocationData('Lisbon', dataService),
  LocationData('Providence', dataService),
  LocationData('The Hague', dataService),
  LocationData('Edinburgh', dataService),
  LocationData('St Louis', dataService),
  LocationData('Honolulu', dataService),
];
