import 'package:one_app/utils/location_data.dart';

final allLocations = <LocationData>[
  LocationData(city: 'New York'),
  LocationData(city: 'Tokyo'),
  LocationData(city: 'London'),
  LocationData(city: 'Los Angeles'),
  LocationData(city: 'Singapore'),
  LocationData(city: 'Paris'),
  LocationData(city: 'Chicago'),
  LocationData(city: 'Boston'),
  LocationData(city: 'San Francisco'),
  LocationData(city: 'Toronto'),
  LocationData(city: 'Melbourne'),
  LocationData(city: 'Berlin'),
  LocationData(city: 'Dallas'),
  LocationData(city: 'Seoul'),
  LocationData(city: 'Sydney'),
  LocationData(city: 'Seattle'),
  LocationData(city: 'Houston'),
  LocationData(city: 'Atlanta'),
  LocationData(city: 'Washington DC'),
  LocationData(city: 'Miami'),
  LocationData(city: 'Barcelona'),
  LocationData(city: 'Montréal'),
  LocationData(city: 'San Diego'),
  LocationData(city: 'Philadelphia'),
  LocationData(city: 'Vienna'),
  LocationData(city: 'Beijing'),
  LocationData(city: 'Munich'),
  LocationData(city: 'Madrid'),
  LocationData(city: 'Milan'),
  LocationData(city: 'Amsterdam'),
  LocationData(city: 'Dubai'),
  LocationData(city: 'Stockholm'),
  LocationData(city: 'Shanghai'),
  LocationData(city: 'Austin'),
  LocationData(city: 'Denver'),
  LocationData(city: 'Vancouver'),
  LocationData(city: 'Osaka'),
  LocationData(city: 'Moscow'),
  LocationData(city: 'Portland'),
  LocationData(city: 'Las Vegas'),
  LocationData(city: 'Tel Aviv'),
  LocationData(city: 'Oslo'),
  LocationData(city: 'Istanbul'),
  LocationData(city: 'Taipei'),
  LocationData(city: 'Rome'),
  LocationData(city: 'Hamburg'),
  LocationData(city: 'Copenhagen'),
  LocationData(city: 'Brisbane'),
  LocationData(city: 'Oakland'),
  LocationData(city: 'Orlando'),
  LocationData(city: 'Baltimore'),
  LocationData(city: 'Dublin'),
  LocationData(city: 'Shenzhen'),
  LocationData(city: 'Québec'),
  LocationData(city: 'Detroit'),
  LocationData(city: 'Hong Kong'),
  LocationData(city: 'Manchester'),
  LocationData(city: 'Helsinki'),
  LocationData(city: 'Minneapolis'),
  LocationData(city: 'Phoenix'),
  LocationData(city: 'Prague'),
  LocationData(city: 'Zürich'),
  LocationData(city: 'Frankfurt'),
  LocationData(city: 'Sacramento'),
  LocationData(city: 'Brussels'),
  LocationData(city: 'Nashville'),
  LocationData(city: 'São Paulo'),
  LocationData(city: 'Newark'),
  LocationData(city: 'Buenos Aires'),
  LocationData(city: 'San Antonio'),
  LocationData(city: 'Bangkok'),
  LocationData(city: 'Santa Ana'),
  LocationData(city: 'Tampa'),
  LocationData(city: 'Guangzhou'),
  LocationData(city: 'Abu Dhabi'),
  LocationData(city: 'Lyon'),
  LocationData(city: 'Düsseldorf'),
  LocationData(city: 'Athens'),
  LocationData(city: 'Budapest'),
  LocationData(city: 'Kyoto'),
  LocationData(city: 'Kuala Lumpur'),
  LocationData(city: 'Stuttgart'),
  LocationData(city: 'Rotterdam'),
  LocationData(city: 'Fort Lauderdale'),
  LocationData(city: 'Mumbai'),
  LocationData(city: 'Charlotte'),
  LocationData(city: 'Mexico City'),
  LocationData(city: 'Riverside'),
  LocationData(city: 'Calgary'),
  LocationData(city: 'Pittsburgh'),
  LocationData(city: 'Busan'),
  LocationData(city: 'Cologne'),
  LocationData(city: 'Raleigh'),
  LocationData(city: 'Kansas City'),
  LocationData(city: 'Lisbon'),
  LocationData(city: 'Providence'),
  LocationData(city: 'The Hague'),
  LocationData(city: 'Edinburgh'),
  LocationData(city: 'St Louis'),
  LocationData(city: 'Honolulu'),
];
