import 'package:one_app/utils/city_data.dart';

final allLocations = <CityData>[
  CityData(city: 'New York'),
  CityData(city: 'Tokyo'),
  CityData(city: 'London'),
  CityData(city: 'Los Angeles'),
  CityData(city: 'Singapore'),
  CityData(city: 'Paris'),
  CityData(city: 'Chicago'),
  CityData(city: 'Boston'),
  CityData(city: 'San Francisco'),
  CityData(city: 'Toronto'),
  CityData(city: 'Melbourne'),
  CityData(city: 'Berlin'),
  CityData(city: 'Dallas'),
  CityData(city: 'Seoul'),
  CityData(city: 'Sydney'),
  CityData(city: 'Seattle'),
  CityData(city: 'Houston'),
  CityData(city: 'Atlanta'),
  CityData(city: 'Washington DC'),
  CityData(city: 'Miami'),
  CityData(city: 'Barcelona'),
  CityData(city: 'Montréal'),
  CityData(city: 'San Diego'),
  CityData(city: 'Philadelphia'),
  CityData(city: 'Vienna'),
  CityData(city: 'Beijing'),
  CityData(city: 'Munich'),
  CityData(city: 'Madrid'),
  CityData(city: 'Milan'),
  CityData(city: 'Amsterdam'),
  CityData(city: 'Dubai'),
  CityData(city: 'Stockholm'),
  CityData(city: 'Shanghai'),
  CityData(city: 'Austin'),
  CityData(city: 'Denver'),
  CityData(city: 'Vancouver'),
  CityData(city: 'Osaka'),
  CityData(city: 'Moscow'),
  CityData(city: 'Portland'),
  CityData(city: 'Las Vegas'),
  CityData(city: 'Tel Aviv'),
  CityData(city: 'Oslo'),
  CityData(city: 'Istanbul'),
  CityData(city: 'Taipei'),
  CityData(city: 'Rome'),
  CityData(city: 'Hamburg'),
  CityData(city: 'Copenhagen'),
  CityData(city: 'Brisbane'),
  CityData(city: 'Oakland'),
  CityData(city: 'Orlando'),
  CityData(city: 'Baltimore'),
  CityData(city: 'Dublin'),
  CityData(city: 'Shenzhen'),
  CityData(city: 'Québec'),
  CityData(city: 'Detroit'),
  CityData(city: 'Hong Kong'),
  CityData(city: 'Manchester'),
  CityData(city: 'Helsinki'),
  CityData(city: 'Minneapolis'),
  CityData(city: 'Phoenix'),
  CityData(city: 'Prague'),
  CityData(city: 'Zürich'),
  CityData(city: 'Frankfurt'),
  CityData(city: 'Sacramento'),
  CityData(city: 'Brussels'),
  CityData(city: 'Nashville'),
  CityData(city: 'São Paulo'),
  CityData(city: 'Newark'),
  CityData(city: 'Buenos Aires'),
  CityData(city: 'San Antonio'),
  CityData(city: 'Bangkok'),
  CityData(city: 'Santa Ana'),
  CityData(city: 'Tampa'),
  CityData(city: 'Guangzhou'),
  CityData(city: 'Abu Dhabi'),
  CityData(city: 'Lyon'),
  CityData(city: 'Düsseldorf'),
  CityData(city: 'Athens'),
  CityData(city: 'Budapest'),
  CityData(city: 'Kyoto'),
  CityData(city: 'Kuala Lumpur'),
  CityData(city: 'Stuttgart'),
  CityData(city: 'Rotterdam'),
  CityData(city: 'Fort Lauderdale'),
  CityData(city: 'Mumbai'),
  CityData(city: 'Charlotte'),
  CityData(city: 'Mexico City'),
  CityData(city: 'Riverside'),
  CityData(city: 'Calgary'),
  CityData(city: 'Pittsburgh'),
  CityData(city: 'Busan'),
  CityData(city: 'Cologne'),
  CityData(city: 'Raleigh'),
  CityData(city: 'Kansas City'),
  CityData(city: 'Lisbon'),
  CityData(city: 'Providence'),
  CityData(city: 'The Hague'),
  CityData(city: 'Edinburgh'),
  CityData(city: 'St Louis'),
  CityData(city: 'Honolulu'),
];
